Add block for 6.8.2 to helper library
sous-chefs/confluence pull request #166
Opened 2018-10-24 14:00 UTC by alzayatm

## Description
Add a block for 6.8.2 to helper library -- includes SHA-256 checksums

### Issues Resolved
Addition of new confluence version (6.8.2)

### Check List
- [X] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [X] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2018-10-26 09:26 UTC, anuriq commented on metadata.rb
> +version '2.5.1'
version is usually bumped after merge, no?

2018-10-26 09:39 UTC, damacus requested changes
Please don't bump the version without either asking.

2018-10-26 12:35 UTC, alzayatm commented
I did bump the version. Are you expecting a major or a minor version bump?

2018-10-29 19:51 UTC, alzayatm commented
What is the status on this?

2018-11-02 06:44 UTC, anuriq commented
> What is the status on this?

Hi @alzayatm 
@damacus  requested a change in the PR. Version of the cookbook is bumped after merge, before cookbook release. There may be a lot of changes during a cookbook release, if every PR bumps version, we will have inconsistent chain of versions.
Thank you.

2018-11-02 18:27 UTC, alzayatm commented
> > What is the status on this?
> 
> Hi @alzayatm
> @damacus requested a change in the PR. Version of the cookbook is bumped after merge, before cookbook release. There may be a lot of changes during a cookbook release, if every PR bumps version, we will have inconsistent chain of versions.
> Thank you.

Understood. I changed the version back to 2.5.0. Can you guys accept the pull request now?

2018-11-07 08:16 UTC, anuriq commented
LGTM
@damacus

2018-11-08 21:19 UTC, alzayatm commented
Can we please approve this?

2018-11-19 14:53 UTC, alzayatm commented
Following up again.

2018-11-26 20:44 UTC, merged